name: Deploy Service

on:
  workflow_dispatch:
    inputs:
      service:
        description: Service Name
        type: string
        required: true

jobs:
  plan-dev:
    name: Plan Development
    runs-on: ubuntu-latest
    steps:
      - name: Plan ${{ inputs.service }}
        run: echo Planning ${{ inputs.service }}

  apply-dev:
    name: Apply Development
    runs-on: ubuntu-latest
    needs: plan-dev
    environment: ${{ inputs.service }}-dev
    steps:
      - name: Apply ${{ inputs.service }}
        run: echo Applying ${{ inputs.service }}

  plan-stg:
    name: Plan Staging
    runs-on: ubuntu-latest
    needs: apply-dev
    steps:
      - name: Plan ${{ inputs.service }}
        run: echo Planning ${{ inputs.service }}

  apply-stg:
    name: Apply Staging
    runs-on: ubuntu-latest
    needs: plan-stg
    environment: ${{ inputs.service }}-stg
    steps:
      - name: Apply ${{ inputs.service }}
        run: echo Applying ${{ inputs.service }}

  plan-prd:
    name: Plan Production
    runs-on: ubuntu-latest
    needs: apply-stg
    steps:
      - name: Plan ${{ inputs.service }}
        run: echo Planning ${{ inputs.service }}

  apply-prd:
    name: Apply Production
    runs-on: ubuntu-latest
    needs: plan-prd
    environment: ${{ inputs.service }}-prd
    steps:
      - name: Apply Deploy ${{ inputs.service }}
        run: echo Applying ${{ inputs.service }}
